language: go
go_import_path: darlinggo.co/tokens

go:
  - 1.6
before_script: 
  - psql -c 'create database travis_ci_test;' -U postgres
  - go get -u github.com/paddyforan/combinedcoverage
  - go get -u github.com/wadey/gocovmerge
env:
  - PG_TEST_DB="postgres://postgres:@localhost/travis_ci_test?sslmode=disable"
script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go list ./... | grep -v /vendor/ | xargs -L1 golint
  - ./coverage.sh

services:
  - postgresql

addons:
  postgresql: "9.3"
